Repository five-per-week/algorithms, pull requests merged in 2020-10, with the labels that each got.

#28 ✅ solved: Programmers 42583 @younho9
  problems/programmers/42583-a-bridge-truck/README.md
  problems/programmers/42583-a-bridge-truck/younho9.js
  problems/programmers/42583-a-bridge-truck/younho9.test.js
Labels: algorithm

#29 ✅ solved: Programmers 42587 @younho9
  problems/programmers/42587-printer/README.md
  problems/programmers/42587-printer/younho9.js
  problems/programmers/42587-printer/younho9.test.js
Labels: algorithm

#34 ✅ solved: Programmers 42626 @younho9
  problems/programmers/42626-spicier/README.md
  problems/programmers/42626-spicier/younho9.js
  problems/programmers/42626-spicier/younho9.py
  problems/programmers/42626-spicier/younho9.test.js
Labels: algorithm

#36 ✅ solved: Programmers 42628 @younho9
  problems/programmers/42628-double-priority-queue/README.md
  problems/programmers/42628-double-priority-queue/younho9.js
  problems/programmers/42628-double-priority-queue/younho9.test.js
Labels: algorithm

#30 ✅ solved: Programmers 42586 @agrajak
  problems/leetcode/198-house-robber/README.md
  problems/leetcode/198-house-robber/agrajak.py
  problems/programmers/42586-feature-develop/agrajak.py
Labels: algorithm

#31 ✅ solved: Leetcode 83 @agrajak
  problems/leetcode/83-remove-duplicates-from-sorted-list/README.md
  problems/leetcode/83-remove-duplicates-from-sorted-list/agrajak.py
Labels: algorithm

#33 ✅ solved: Leetcode 110 @agrajak
  problems/leetcode/110-balanced-binary-tree/README.md
  problems/leetcode/110-balanced-binary-tree/agrajak.py
Labels: algorithm

#32 ✅ solved: Leetcode 67 @agrajak
  problems/leetcode/67-add-binary/README.md
  problems/leetcode/67-add-binary/agrajak.py
Labels: algorithm

#38 ✅ solved: Programmers 42748 @younho9
  problems/programmers/42748-kth-number/README.md
  problems/programmers/42748-kth-number/younho9.js
  problems/programmers/42748-kth-number/younho9.test.js
Labels: algorithm

#41 ✅ solved: Programmers 42747 @younho9
  problems/programmers/42747-h-index/README.md
  problems/programmers/42747-h-index/younho9.js
  problems/programmers/42747-h-index/younho9.test.js
Labels: algorithm

#42 ✅ solved: Programmers 42840 @younho9
  problems/programmers/42840-mock-test/README.md
  problems/programmers/42840-mock-test/younho9.js
  problems/programmers/42840-mock-test/younho9.test.js
Labels: algorithm

#40 ✅ solved: Programmers 42746 @younho9
  problems/programmers/42746-largest-number/README.md
  problems/programmers/42746-largest-number/younho9.js
  problems/programmers/42746-largest-number/younho9.test.js
Labels: algorithm

#44 ✅ solved: Programmers 42842 @younho9
  problems/programmers/42842-carpet/README.md
  problems/programmers/42842-carpet/images/carpet.png
  problems/programmers/42842-carpet/younho9.js
  problems/programmers/42842-carpet/younho9.test.js
Labels: algorithm

#45 ✅ solved: Programmers 42862 @younho9
  problems/programmers/42862-training-clothes/README.md
  problems/programmers/42862-training-clothes/younho9.js
  problems/programmers/42862-training-clothes/younho9.test.js
Labels: algorithm

#43 ✅ solved: Programmers 42839 @younho9
  problems/programmers/42839-find-prime-number/README.md
  problems/programmers/42839-find-prime-number/younho9.js
  problems/programmers/42839-find-prime-number/younho9.test.js
Labels: algorithm

#46 ✅ solved: Leetcode 268 @agrajak
  problems/leetcode/268-missing-number/README.md
  problems/leetcode/268-missing-number/agrajak.py
Labels: algorithm

#47 ✅ solved: Leetcode 703 @agrajak
  problems/leetcode/703-kth-largest-element-in-a-stream/README.md
  problems/leetcode/703-kth-largest-element-in-a-stream/agrajak.py
Labels: algorithm, recommendation

#48 ✅ solved: Leetcode 459 @agrajak
  problems/leetcode/459-repeated-substring-pattern/README.md
  problems/leetcode/459-repeated-substring-pattern/agrajak.py
Labels: algorithm, recommendation

#50 ✅ solved: Leetcode 1 @jungcome7
  problems/leetcode/1-two-sum/README.md
  problems/leetcode/1-two-sum/jungcome7.js
Labels: algorithm

#51 ✅ solved: Leetcode 104 @jungcome7
  problems/leetcode/104-maximum-depth-of-binary-tree/README.md
  problems/leetcode/104-maximum-depth-of-binary-tree/jungcome7.js
Labels: algorithm

#53 ✅ solved: Programmers 42860 @younho9
  problems/programmers/42860-joystick/README.md
  problems/programmers/42860-joystick/younho9.js
  problems/programmers/42860-joystick/younho9.test.js
Labels: algorithm, need refactor

#54 ✅ solved: hackerrank encryption @jungcome7
  problems/hackerrank/encryption/encryption-English.pdf
  problems/hackerrank/encryption/jungcome7.js
Labels: algorithm

#55 ✅ solved: Programmers 42885 @younho9
  problems/programmers/42885-lifeboat/README.md
  problems/programmers/42885-lifeboat/younho9.js
  problems/programmers/42885-lifeboat/younho9.test.js
Labels: algorithm

#56 ✅ solved: Programmers 43165 @younho9
  problems/programmers/43165-target-number/README.md
  problems/programmers/43165-target-number/younho9.js
  problems/programmers/43165-target-number/younho9.test.js
Labels: algorithm
