Repository five-per-week/algorithms, pull requests merged in 2020-09, with the labels that each got.

#3 docs: Add github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#6 ✅ younho9: Solved programmers-42576
  problems/programmers/42576-an-uncompleted-player/README.md
  problems/programmers/42576-an-uncompleted-player/younho9.js
  problems/programmers/42576-an-uncompleted-player/younho9.test.js
Labels: algorithm

#7 풀 리퀘스트 템플릿에 문제 해결 유무도 추가함
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#12 chore: Add create-ps-directory to devDependencies
  package-lock.json
  package.json
Labels: enhancement

#9 ✅ solved: Programmers 42577 @younho9
  problems/programmers/42577-list-of-telephone/README.md
  problems/programmers/42577-list-of-telephone/younho9.js
  problems/programmers/42577-list-of-telephone/younho9.py
  problems/programmers/42577-list-of-telephone/younho9.test.js
Labels: algorithm

#10 ✅ solved: Programmers 42578 @younho9
  problems/programmers/42578-camouflage/README.md
  problems/programmers/42578-camouflage/younho9.js
  problems/programmers/42578-camouflage/younho9.test.js
Labels: algorithm

#8 docs: Add study rules
  README.md
Labels: documentation

#13 ✅ solved: Programmers 42579 @younho9
  problems/programmers/42579-best-album/README.md
  problems/programmers/42579-best-album/younho9.js
  problems/programmers/42579-best-album/younho9.test.js
Labels: algorithm

#14 ✅ solved: Programmers 42577 @agrajak
  problems/programmers/42577-list-of-telephone/agrajak.py
Labels: algorithm

#18 ✅ solved: Leetcode Best Time to Buy and Sell Stock @agrajak
  problems/leetcode/121-best-time-to-buy-and-sell-stock/README.md
  problems/leetcode/121-best-time-to-buy-and-sell-stock/agrajak.py
Labels: algorithm

#19 feat: implement generate-doc.js prototype (#2)
  .github/workflows/auto-update-readme.yml
  README.md
  generate-docs.js
  package-lock.json
  package.json
Labels: documentation

#22 Refactor/docs generator rename
  generate-docs.js
Labels: documentation

#24 ✅ solved: Programmers 42584 @younho9
  problems/programmers/42584-stock-price/README.md
  problems/programmers/42584-stock-price/younho9.js
  problems/programmers/42584-stock-price/younho9.py
  problems/programmers/42584-stock-price/younho9.test.js
Labels: algorithm

#27 ✅ solved: Programmers 42586 @younho9
  problems/programmers/42586-feature-develop/README.md
  problems/programmers/42586-feature-develop/younho9.js
  problems/programmers/42586-feature-develop/younho9.test.js
Labels: algorithm
